name: clocktrain
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev.

# Version and build number
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Icons and UI elements
  cupertino_icons: ^1.0.6
  google_fonts: ^4.0.4 # Custom fonts from Google Fonts

  # State management
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  flutter_riverpod: ^2.5.1 # Integration with Flutter

  # Code generation and annotations
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  build_runner: ^2.4.10 # Required for code generation

  # Routing and navigation
  go_router: ^14.2.1

  # Localization and internationalization
  flutter_localizations:
    sdk: flutter
  intl: any # Localization and date formatting support

  # Audio and video playback
  audioplayers: ^1.1.1
  youtube_player_flutter: ^9.1.1 # YouTube video embedding

  # Persistent storage
  shared_preferences: ^2.3.2

  # Firebase services
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4 # Cloud storage for assets

  # JSON serialization
  json_annotation: ^4.9.0 # Annotations for JSON serialization
  logger: ^2.4.0
  path_provider: ^2.1.5
  flutter_svg: ^2.0.9
  sqflite: ^2.4.1
  path: ^1.9.0
  drift: ^2.21.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting and code quality
  flutter_lints: ^4.0.0 # Recommended lints for Flutter
  # analyzer: ^6.11.0
  custom_lint: # Custom lint rules
  riverpod_lint: ^2.3.10
  riverpod_generator: ^2.4.0 # Generates Riverpod providers
  json_serializable: ^6.8.0

flutter:
  generate: true
  uses-material-design: true # Includes Material Icons font

  # Asset management
  assets:
    - assets/ # General assets folder
    - assets/sounds/ # Folder for sound files
    - assets/icon/ # Folder for app icons
    - assets/mock/ # Folder for mock data