name: clocktrain
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev.

# Version and build number
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  # Icons and UI elements
  cupertino_icons: ^1.0.8
  google_fonts: ^4.0.4 # Custom fonts from Google Fonts

  # State management
  flutter_riverpod: ^2.6.1 # Integration with Flubretter

  # Code generation and annotations
  freezed_annotation: ^2.4.4

  # Routing and navigation
  go_router: ^14.2.1

  # Localization and internationalization
  flutter_localizations:
    sdk: flutter
  intl: any # Localization and date formatting support

  # Audio and video playback
  audioplayers: ^6.1.0
  youtube_player_flutter: ^9.1.1 # YouTube video embedding

  # JSON serialization
  json_annotation: ^4.9.0 # Annotations for JSON serialization

  # Logging and debugging
  logger: ^2.4.0

  # Image and file handling
  path_provider: ^2.1.5
  flutter_svg: ^2.0.9
  # path: ^1.9.0

  # Database
  drift: ^2.21.0
  drift_flutter: ^0.2.1
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting and code quality
  flutter_lints: ^4.0.0 # Recommended lints for Flutter
  # Riverpod
  riverpod_lint: ^2.6.3
  # Json serialization
  json_serializable: ^6.8.0
  # Freezed
  freezed: ^2.5.7
  # Database
  drift_dev: ^2.21.0
  # Code generation
  build_runner: ^2.4.13

flutter:
  generate: true
  uses-material-design: true # Includes Material Icons font

  # Asset management
  assets:
    - assets/ # General assets folder
    - assets/sounds/ # Folder for sound files
    - assets/icon/ # Folder for app icons
    - assets/mock/ # Folder for mock data
  
  # Script
scripts: 
  br_localDb: ./build_runner.sh localDb
  # pre-build:
  #   - flutter pub run build_runner build --delete-conflicting-outputs
  # post-build:
  #   - flutter pub run build_runner build --delete-conflicting-outputs