name: app_feature_login
description: "Module to manage login feature"
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  #UI
  flutter_svg: ^2.0.16

  #Path Provider
  path_provider: ^2.1.5 

  # State management
  
  flutter_riverpod: ^2.6.1
  
  # Code generation and annotations
  freezed_annotation: ^2.4.4 
  
  # JSON serialization
  json_annotation: ^4.9.0 
  
  #Funtional programming
  dartz: ^0.10.1
  
  # Routing and navigation
  go_router: ^14.6.1

  #DATA
  uuid: ^4.5.1

  app_shared:
    path: ../../app_shared
  app_data:
    path: ../../app_data
  app_feature_workout:
    path: ../../app_features/app_feature_workout

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Riverpod
  riverpod_lint: ^2.6.3 
  # Json serialization
  json_serializable: ^6.8.0 
  # Freezed
  freezed: ^2.5.7 
  # Code generation
  build_runner: ^2.4.13 