name: app_feature_login
description: "Module to manage login feature"
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #Path Provider
  path_provider: 

  # State management
  flutter_riverpod: 
  
  # Code generation and annotations
  freezed_annotation: 
  
  # JSON serialization
  json_annotation: 
  
  #Funtional programming
  dartz:
  
  # Routing and navigation
  go_router:

  app_shared:
    path: ../../app_shared
  app_data:
    path: ../../app_data

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Riverpod
  riverpod_lint: 
  # Json serialization
  json_serializable: 
  # Freezed
  freezed: 
  # Code generation
  build_runner: 