include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

linter:
  rules:
    - sort_constructors_first
    - prefer_initializing_formals
    - always_put_required_named_parameters_first
    - sort_child_properties_last
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_single_quotes
    - avoid_print
    - avoid_redundant_argument_values
    - avoid_unnecessary_containers
    - avoid_types_on_closure_parameters
    - prefer_typing_uninitialized_variables
    - prefer_is_not_empty
    - prefer_is_empty
    - prefer_interpolation_to_compose_strings
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_asserts_with_message
    - prefer_asserts_in_initializer_lists
    - prefer_adjacent_string_concatenation
    - prefer_const_declarations
    - prefer_const_constructors_in_immutables