name: app_shared
description: "Module to manage shared code"
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Localization and internationalization
  flutter_localizations:
    sdk: flutter
  intl: any

  # UI
  flutter_svg: ^2.0.16
  google_fonts: ^6.2.1

  # Logging
  logger: ^2.5.0

   #Path Provider
  path_provider: 

  # State management
  flutter_riverpod: 
  
  # Code generation and annotations
  freezed_annotation: 
  
  # JSON serialization
  json_annotation: 
  
  #Funtional programming
  dartz:
  
  # Routing and navigation
  go_router:

  # features
  app_feature_login:
    path: ../app_features/app_feature_login

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Riverpod
  riverpod_lint: 
  # Json serialization
  json_serializable: 
  # Freezed
  freezed: 
  # Code generation
  build_runner: 

scripts: 
  br_login: ./build_runner.sh localDb