name: app_shared
description: "A new Flutter package project."
version: 0.0.1
homepage: ' '

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  google_fonts: ^6.2.1
  logger: ^2.5.0
  path_provider: ^2.1.5

  # State management
  flutter_riverpod: ^2.6.1 # Integration with Flubretter
  
  # Code generation and annotations
  freezed_annotation: ^2.4.4
  
  # JSON serialization
  json_annotation: ^4.9.0 # Annotations for JSON serialization

  # Localization and internationalization
  flutter_localizations:
    sdk: flutter
  intl: any # Localization and date formatting support
  
  #Funtional programming
  dartz: ^0.10.1
  
  # Routing and navigation
  go_router: ^14.6.1

  # features
  app_feature_login:
    path: ../app_features/app_feature_login

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # Riverpod
  riverpod_lint: ^2.6.3
  # Json serialization
  json_serializable: ^6.8.0
  # Freezed
  freezed: ^2.5.7
  # Code generation
  build_runner: ^2.4.13

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
# flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
scripts: 
  br_login: ./build_runner.sh localDb