name: app_shared
description: "Module to manage shared code"
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Localization and internationalization
  flutter_localizations:
    sdk: flutter
  intl: any

  # UI
  flutter_svg: ^2.0.16
  google_fonts: ^6.2.1

  # Logging
  logger: ^2.5.0

   #Path Provider
  path_provider: ^2.1.5 

  # State management
  flutter_riverpod: ^2.6.1
  
  # Code generation and annotations
  freezed_annotation: ^2.4.4 
  
  # JSON serialization
  json_annotation: ^4.9.0 
  
  #Funtional programming
  dartz: ^0.10.1
  
  # Routing and navigation
  go_router: ^14.6.1

  # features
  app_feature_login:
    path: ../app_features/app_feature_login
  app_feature_workout:
    path: ../app_features/app_feature_workout

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Riverpod
  riverpod_lint: ^2.6.3 
  # Json serialization
  json_serializable: ^6.8.0 
  # Freezed
  freezed: ^2.5.7 
  # Code generation
  build_runner: ^2.4.13 
  # Flutter Gen
  flutter_gen_runner: ^5.8.0

flutter_gen:
  output: lib/gen/
  line_length: 80

  # Optional
  integrations:
    flutter_svg: true

  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
      class_name: SharedAssets

flutter:
  assets:
    - assets/ # General assets folder
    - assets/icons/ # Folder for app icons
    - assets/sounds/ # Folder for sound files

scripts: 
  br_login: ./build_runner.sh localDb