name: app_main
description: "Module to manage entrypoint of the app"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Path Provider
  path_provider: 

  # State management
  flutter_riverpod: 
  
  # Code generation and annotations
  freezed_annotation: 
  
  # JSON serialization
  json_annotation: 
  
  #Funtional programming
  dartz:
  
  # Routing and navigation
  go_router:
  
  # Local Db
  realm: ^20.0.0

  app_shared:
    path: ../app_shared

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Riverpod
  riverpod_lint: 
  # Json serialization
  json_serializable: 
  # Freezed
  freezed: 
  # Code generation
  build_runner: 

  flutter_flavorizr: ^2.2.3


flutter:
  uses-material-design: true