name: widgetbook
description: "A new Flutter project."
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Local Db
  realm: ^20.0.0

  # features
  app_shared:
    path: ../../app_shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

asset:
  - packages/app_shared/assets/icon/

flutter:
  uses-material-design: true